# Generated by Django 5.2.3 on 2025-11-29 20:55

import negocios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_diadescanso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='horario_atencion',
            field=models.JSONField(blank=True, default=negocios.models.horario_default, null=True),
        ),
    ]
