# Generated by Django 5.2.3 on 2025-11-29 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_sistema_financiero'),
        ('negocios', '0010_horario_default_10_22'),
        ('profesionales', '0005_alter_notificacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comision', models.CharField(choices=[('porcentaje', 'Porcentaje del servicio'), ('fijo', 'Monto fijo por servicio')], default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: 0-100. Si es fijo: monto en pesos.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_profesionales', to='negocios.negocio')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Comisión de Profesional',
                'verbose_name_plural': 'Comisiones de Profesionales',
                'unique_together': {('profesional', 'negocio')},
            },
        ),
        migrations.CreateModel(
            name='ResumenFinancieroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('ingresos_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_suscripciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comisiones_profesionales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_reservas', models.PositiveIntegerField(default=0)),
                ('reservas_completadas', models.PositiveIntegerField(default=0)),
                ('reservas_canceladas', models.PositiveIntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_financieros', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Resumen Financiero Mensual',
                'verbose_name_plural': 'Resúmenes Financieros Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('negocio', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='TransaccionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('concepto', models.CharField(choices=[('servicio', 'Servicio prestado'), ('suscripcion', 'Pago de suscripción'), ('propina', 'Propina'), ('comision_profesional', 'Comisión a profesional'), ('comision_plataforma', 'Comisión plataforma'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste contable'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_profesional', models.DecimalField(decimal_places=2, default=0, help_text='Monto que corresponde al profesional', max_digits=12)),
                ('comision_negocio', models.DecimalField(decimal_places=2, default=0, help_text='Monto que corresponde al negocio', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='negocios.negocio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='profesionales.profesional')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='clientes.reserva')),
            ],
            options={
                'verbose_name': 'Transacción del Negocio',
                'verbose_name_plural': 'Transacciones del Negocio',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['negocio', 'fecha'], name='negocios_tr_negocio_c87dc0_idx'), models.Index(fields=['profesional', 'fecha'], name='negocios_tr_profesi_8c9221_idx'), models.Index(fields=['tipo', 'concepto'], name='negocios_tr_tipo_68fd5d_idx')],
            },
        ),
    ]
