# Generated by Django 5.2.3 on 2025-08-28 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionRecordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva_confirmada", "Reserva Confirmada"),
                            ("recordatorio_dia_antes", "Recordatorio Día Antes"),
                            ("recordatorio_tres_horas", "Recordatorio 3 Horas Antes"),
                            ("reserva_cancelada", "Reserva Cancelada"),
                            ("reserva_reagendada", "Reserva Reagendada"),
                            ("suscripcion_renovacion", "Renovación de Suscripción"),
                            ("suscripcion_expirada", "Suscripción Expirada"),
                            ("inasistencia", "Inasistencia"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("anticipacion_horas", models.PositiveIntegerField(default=24)),
                ("anticipacion_minutos", models.PositiveIntegerField(default=0)),
                ("canales_habilitados", models.JSONField(default=list)),
                (
                    "template_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "template_whatsapp",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "template_sms",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reintentos_maximos", models.PositiveIntegerField(default=3)),
                ("delay_reintentos_minutos", models.PositiveIntegerField(default=15)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Recordatorio",
                "verbose_name_plural": "Configuraciones de Recordatorios",
                "db_table": "configuracion_recordatorios",
            },
        ),
        migrations.CreateModel(
            name="PlantillaRecordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva_confirmada", "Reserva Confirmada"),
                            ("recordatorio_dia_antes", "Recordatorio Día Antes"),
                            ("recordatorio_tres_horas", "Recordatorio 3 Horas Antes"),
                            ("reserva_cancelada", "Reserva Cancelada"),
                            ("reserva_reagendada", "Reserva Reagendada"),
                            ("suscripcion_renovacion", "Renovación de Suscripción"),
                            ("suscripcion_expirada", "Suscripción Expirada"),
                            ("inasistencia", "Inasistencia"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("asunto", models.CharField(max_length=255)),
                ("mensaje_texto", models.TextField()),
                ("mensaje_html", models.TextField(blank=True, null=True)),
                ("variables_disponibles", models.JSONField(default=list)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Recordatorio",
                "verbose_name_plural": "Plantillas de Recordatorios",
                "db_table": "plantillas_recordatorios",
            },
        ),
        migrations.CreateModel(
            name="Recordatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva_confirmada", "Reserva Confirmada"),
                            ("recordatorio_dia_antes", "Recordatorio Día Antes"),
                            ("recordatorio_tres_horas", "Recordatorio 3 Horas Antes"),
                            ("reserva_cancelada", "Reserva Cancelada"),
                            ("reserva_reagendada", "Reserva Reagendada"),
                            ("suscripcion_renovacion", "Renovación de Suscripción"),
                            ("suscripcion_expirada", "Suscripción Expirada"),
                            ("inasistencia", "Inasistencia"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("fallido", "Fallido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("asunto", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("mensaje_html", models.TextField(blank=True, null=True)),
                ("fecha_programada", models.DateTimeField()),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("canales_habilitados", models.JSONField(default=list)),
                ("canales_enviados", models.JSONField(default=dict)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("reintentos_maximos", models.PositiveIntegerField(default=3)),
                ("reintentos_actuales", models.PositiveIntegerField(default=0)),
                ("prioridad", models.PositiveIntegerField(default=5)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contexto_template", models.JSONField(default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordatorios_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordatorios_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio",
                "verbose_name_plural": "Recordatorios",
                "db_table": "recordatorios",
                "ordering": ["-fecha_programada", "-prioridad"],
            },
        ),
        migrations.CreateModel(
            name="HistorialRecordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50)),
                (
                    "canal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("detalles", models.JSONField(default=dict)),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                ("fecha_accion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recordatorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="recordatorios.recordatorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Recordatorio",
                "verbose_name_plural": "Historial de Recordatorios",
                "db_table": "historial_recordatorios",
                "ordering": ["-fecha_accion"],
            },
        ),
        migrations.AddIndex(
            model_name="recordatorio",
            index=models.Index(
                fields=["estado", "fecha_programada"],
                name="recordatori_estado_cd4ce0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordatorio",
            index=models.Index(
                fields=["tipo", "destinatario"], name="recordatori_tipo_f7248c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordatorio",
            index=models.Index(
                fields=["fecha_programada"], name="recordatori_fecha_p_bf22b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordatorio",
            index=models.Index(fields=["estado"], name="recordatori_estado_89e682_idx"),
        ),
    ]
