# Generated by Django 5.2.3 on 2025-11-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_usuariopersonalizado_fecha_nacimiento_and_more'),
        ('negocios', '0009_diadescanso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('abierto', 'Abierto'), ('clickeado', 'Clickeado'), ('rebotado', 'Rebotado'), ('fallido', 'Fallido')], default='enviado', max_length=20)),
                ('proveedor', models.CharField(choices=[('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES'), ('smtp', 'SMTP')], max_length=20)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('abierto_en', models.DateTimeField(blank=True, null=True)),
                ('clickeado_en', models.DateTimeField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('context_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Tracking',
                'verbose_name_plural': 'Emails Tracking',
                'db_table': 'email_tracking',
                'indexes': [models.Index(fields=['estado'], name='email_track_estado_f4cd03_idx'), models.Index(fields=['proveedor'], name='email_track_proveed_691fde_idx'), models.Index(fields=['enviado_en'], name='email_track_enviado_b1a164_idx'), models.Index(fields=['recipient'], name='email_track_recipie_32bae5_idx')],
            },
        ),
    ]
