# Generated by Django 5.2.3 on 2026-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0014_businesscheckoutintent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respuestaticket",
            options={},
        ),
        migrations.RemoveField(
            model_name="respuestaticket",
            name="archivos_adjuntos",
        ),
        migrations.AlterField(
            model_name="businesscheckoutintent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
