# Generated by Django 5.2.3 on 2025-11-29 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_alter_reserva_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeFidelizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('confirmacion_reserva', 'Confirmación de Reserva'), ('recordatorio_24h', 'Recordatorio 24 Horas Antes'), ('recordatorio_1h', 'Recordatorio 1 Hora Antes')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora en que se debe enviar el mensaje')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje de WhatsApp')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_fidelizacion', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_fidelizacion', to='clientes.reserva')),
            ],
            options={
                'verbose_name': 'Mensaje de Fidelización',
                'verbose_name_plural': 'Mensajes de Fidelización',
                'db_table': 'fidelizacion_mensajes',
                'ordering': ['fecha_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='fidelizacio_estado_6a994b_idx'), models.Index(fields=['tipo', 'reserva'], name='fidelizacio_tipo_bb6bc6_idx'), models.Index(fields=['fecha_programada'], name='fidelizacio_fecha_p_33de60_idx')],
            },
        ),
    ]
