# Generated by Django 5.2.3 on 2025-08-20 02:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("negocios", "0009_diadescanso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del plan (ej: Básico, Premium, VIP)",
                        max_length=100,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(help_text="Descripción detallada del plan"),
                ),
                (
                    "precio_mensual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio mensual en la moneda local",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si el plan está disponible para suscripciones",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "max_servicios_mes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = ilimitado, otro número = límite mensual",
                    ),
                ),
                (
                    "descuento_servicios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Porcentaje de descuento en servicios (0-100)",
                    ),
                ),
                (
                    "prioridad_reservas",
                    models.BooleanField(
                        default=False,
                        help_text="Si los suscriptores tienen prioridad en reservas",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_suscripcion",
                        to="negocios.negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Suscripción",
                "verbose_name_plural": "Planes de Suscripción",
                "ordering": ["precio_mensual"],
                "unique_together": {("negocio", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="BeneficioSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "tipo_beneficio",
                    models.CharField(
                        choices=[
                            ("descuento", "Descuento"),
                            ("servicio_gratis", "Servicio Gratis"),
                            ("prioridad", "Prioridad"),
                            ("exclusivo", "Exclusivo"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="Valor del beneficio (ej: 20%, 1 servicio, etc.)",
                        max_length=100,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios",
                        to="suscripciones.plansuscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficio de Suscripción",
                "verbose_name_plural": "Beneficios de Suscripciones",
                "ordering": ["plan", "tipo_beneficio"],
            },
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("cancelada", "Cancelada"),
                            ("expirada", "Expirada"),
                            ("pendiente_pago", "Pendiente de Pago"),
                            ("suspendida", "Suspendida"),
                        ],
                        default="pendiente_pago",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                ("precio_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "moneda",
                    models.CharField(
                        default="COP",
                        help_text="Código de moneda (COP, USD, etc.)",
                        max_length=3,
                    ),
                ),
                ("servicios_utilizados_mes", models.PositiveIntegerField(default=0)),
                (
                    "ultimo_reset_mes",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("renovacion_automatica", models.BooleanField(default=True)),
                ("notificar_antes_renovacion", models.BooleanField(default=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre la suscripción"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="negocios.negocio",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="suscripciones.plansuscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("cliente", "negocio", "plan")},
            },
        ),
        migrations.CreateModel(
            name="PagoSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="COP", max_length=3)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("tarjeta", "Tarjeta de Crédito/Débito"),
                            ("transferencia", "Transferencia Bancaria"),
                            ("efectivo", "Efectivo"),
                            ("pse", "PSE"),
                            ("paypal", "PayPal"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                            ("reembolsado", "Reembolsado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(
                        blank=True,
                        help_text="Referencia o ID de la transacción",
                        max_length=100,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        help_text="Fecha límite para realizar el pago"
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="suscripciones.suscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Suscripción",
                "verbose_name_plural": "Pagos de Suscripciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("creada", "Creada"),
                            ("activada", "Activada"),
                            ("renovada", "Renovada"),
                            ("cancelada", "Cancelada"),
                            ("suspendida", "Suspendida"),
                            ("estado_cambiado", "Estado Cambiado"),
                            ("plan_cambiado", "Plan Cambiado"),
                            ("pago_realizado", "Pago Realizado"),
                            ("pago_fallido", "Pago Fallido"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="suscripciones.suscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Suscripción",
                "verbose_name_plural": "Historial de Suscripciones",
                "ordering": ["-fecha"],
            },
        ),
    ]
