# Generated by Django 5.2.3 on 2025-08-24 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiosuscripcion",
            options={
                "ordering": ["orden", "fecha_creacion"],
                "verbose_name": "Beneficio de Suscripción",
                "verbose_name_plural": "Beneficios de Suscripciones",
            },
        ),
        migrations.AlterUniqueTogether(
            name="beneficiosuscripcion",
            unique_together={("plan", "descripcion")},
        ),
        migrations.AddField(
            model_name="beneficiosuscripcion",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beneficiosuscripcion",
            name="orden",
            field=models.PositiveIntegerField(
                default=0, help_text="Orden de aparición del beneficio"
            ),
        ),
        migrations.AddField(
            model_name="plansuscripcion",
            name="destacado",
            field=models.BooleanField(
                default=False, help_text="Si el plan debe destacarse en la lista"
            ),
        ),
        migrations.AddField(
            model_name="plansuscripcion",
            name="duracion_meses",
            field=models.PositiveIntegerField(
                default=12, help_text="Duración del plan en meses"
            ),
        ),
        migrations.AddField(
            model_name="plansuscripcion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen representativa del plan",
                null=True,
                upload_to="planes_suscripcion/",
            ),
        ),
        migrations.AddField(
            model_name="plansuscripcion",
            name="limite_suscriptores",
            field=models.PositiveIntegerField(
                default=0, help_text="0 = sin límite, otro número = límite máximo"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiosuscripcion",
            name="activo",
            field=models.BooleanField(
                default=True, help_text="Si el beneficio está activo"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiosuscripcion",
            name="descripcion",
            field=models.CharField(
                help_text="Descripción del beneficio", max_length=200
            ),
        ),
        migrations.RemoveField(
            model_name="beneficiosuscripcion",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="beneficiosuscripcion",
            name="tipo_beneficio",
        ),
        migrations.RemoveField(
            model_name="beneficiosuscripcion",
            name="valor",
        ),
    ]
