# Generated by Django 5.2.3 on 2025-11-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_alter_beneficiosuscripcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiosuscripcion',
            options={'ordering': ['orden', 'fecha_creacion'], 'verbose_name': 'Beneficio de Suscripción', 'verbose_name_plural': 'Beneficios de Suscripción'},
        ),
    ]
