# Generated by Django 5.2.3 on 2025-08-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_actividadusuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmado", "Confirmado"),
                    ("cancelado", "Cancelado"),
                    ("completado", "Completado"),
                    ("inasistencia", "Inasistencia"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
