# Generated by Django 5.2.3 on 2025-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('pendiente', 'Pendiente de pago')], default='pendiente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False, help_text='¿El cliente ya pagó?'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del servicio al momento de la reserva', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total a pagar (precio_servicio - descuento)', max_digits=10, null=True),
        ),
    ]
