# Generated by Django 5.2.3 on 2025-11-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_sistema_financiero'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='imagen_referencia',
            field=models.ImageField(blank=True, help_text='Imagen de referencia del corte deseado', null=True, upload_to='reservas/referencias/'),
        ),
    ]
