# Generated by Django 5.2.3 on 2025-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_add_imagen_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_servicio',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del servicio en minutos al momento de la reserva', null=True),
        ),
    ]
