# Generated by Django 5.2.3 on 2026-02-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0013_clienteprovisional_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bloqueocliente",
            new_name="clientes_bl_cliente_533d74_idx",
            old_name="clientes_blo_cliente_2c6d2f_idx",
        ),
        migrations.RenameIndex(
            model_name="bloqueocliente",
            new_name="clientes_bl_negocio_d6a26a_idx",
            old_name="clientes_blo_negocio_62e6c0_idx",
        ),
    ]
