# Generated by Django 5.2.3 on 2025-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacion',
            name='cargo',
            field=models.CharField(blank=True, default='Barbero', help_text='Cargo o rol del profesional en el negocio', max_length=100),
        ),
        migrations.AddField(
            model_name='matriculacion',
            name='salario_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual asignado por el negocio', max_digits=12, null=True),
        ),
    ]
